name: NPM Audit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}
jobs:
  audit:
    permissions:
      contents: read  #  to fetch code (actions/checkout)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PNPM
        run: |
          npm install -g @pnpm/exe@8.3.1

      - name: Run a security audit
        run: pnpm dlx audit-ci --critical --report-type summary

    # - name: Run Dependency confusion supply chain check
    #  run: npx snync -d .
